version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: homecrescent
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homecrescentDb
