export enum Country {
    Nigeria = "Nigeria"
};

export enum State {
    Abia = 'Abia',
    Adamawa = 'Adamawa',
    AkwaIbom = 'Akwa Ibom',
    Anambra = 'Anambra',
    Bauchi = 'Bauchi',
    Bayelsa = 'Bayelsa',
    Benue = 'Benue',
    Borno = 'Borno',
    CrossRiver = 'Cross River',
    Delta = 'Delta',
    Ebonyi = 'Ebonyi',
    Edo = 'Edo',
    Ekiti = 'Ekiti',
    Enugu = 'Enugu',
    Gombe = 'Gombe',
    Imo = 'Imo',
    Jigawa = 'Jigawa',
    Kaduna = 'Kaduna',
    Kano = 'Kano',
    Katsina = 'Katsina',
    Kebbi = 'Kebbi',
    Kogi = 'Kogi',
    Kwara = 'Kwara',
    Lagos = 'Lagos',
    Nasarawa = 'Nasarawa',
    Niger = 'Niger',
    Ogun = 'Ogun',
    Ondo = 'Ondo',
    Osun = 'Osun',
    Oyo = 'Oyo',
    Plateau = 'Plateau',
    Rivers = 'Rivers',
    Sokoto = 'Sokoto',
    Taraba = 'Taraba',
    Yobe = 'Yobe',
    Zamfara = 'Zamfara',
    FCT = 'Federal Capital Territory'
}

export const STATE_DATA: { stateName: string, country: string }[] = [
    { stateName: State.Abia, country: Country.Nigeria },
    { stateName: State.Adamawa, country: Country.Nigeria },
    { stateName: State.AkwaIbom, country: Country.Nigeria },
    { stateName: State.Anambra, country: Country.Nigeria },
    { stateName: State.Bauchi, country: Country.Nigeria },
    { stateName: State.Bayelsa, country: Country.Nigeria },
    { stateName: State.Benue, country: Country.Nigeria },
    { stateName: State.Borno, country: Country.Nigeria },
    { stateName: State.CrossRiver, country: Country.Nigeria },
    { stateName: State.Delta, country: Country.Nigeria },
    { stateName: State.Ebonyi, country: Country.Nigeria },
    { stateName: State.Edo, country: Country.Nigeria },
    { stateName: State.Ekiti, country: Country.Nigeria },
    { stateName: State.Enugu, country: Country.Nigeria },
    { stateName: State.Gombe, country: Country.Nigeria },
    { stateName: State.Imo, country: Country.Nigeria },
    { stateName: State.Jigawa, country: Country.Nigeria },
    { stateName: State.Kaduna, country: Country.Nigeria },
    { stateName: State.Kano, country: Country.Nigeria },
    { stateName: State.Katsina, country: Country.Nigeria },
    { stateName: State.Kebbi, country: Country.Nigeria },
    { stateName: State.Kogi, country: Country.Nigeria },
    { stateName: State.Kwara, country: Country.Nigeria },
    { stateName: State.Lagos, country: Country.Nigeria },
    { stateName: State.Nasarawa, country: Country.Nigeria },
    { stateName: State.Niger, country: Country.Nigeria },
    { stateName: State.Ogun, country: Country.Nigeria },
    { stateName: State.Ondo, country: Country.Nigeria },
    { stateName: State.Osun, country: Country.Nigeria },
    { stateName: State.Oyo, country: Country.Nigeria },
    { stateName: State.Plateau, country: Country.Nigeria },
    { stateName: State.Rivers, country: Country.Nigeria },
    { stateName: State.Sokoto, country: Country.Nigeria },
    { stateName: State.Taraba, country: Country.Nigeria },
    { stateName: State.Yobe, country: Country.Nigeria },
    { stateName: State.Zamfara, country: Country.Nigeria },
    { stateName: State.FCT, country: Country.Nigeria }
];

export enum City {
    Aba = 'Aba',
    Umuahia = 'Umuahia',
    Yola = 'Yola',
    Jimeta = 'Jimeta',
    Uyo = 'Uyo',
    Eket = 'Eket',
    Awka = 'Awka',
    Onitsha = 'Onitsha',
    Bauchi = 'Bauchi',
    Azare = 'Azare',
    Yenagoa = 'Yenagoa',
    Brass = 'Brass',
    Makurdi = 'Makurdi',
    Gboko = 'Gboko',
    Maiduguri = 'Maiduguri',
    Biu = 'Biu',
    Calabar = 'Calabar',
    Ugep = 'Ugep',
    Asaba = 'Asaba',
    Warri = 'Warri',
    Abakaliki = 'Abakaliki',
    Afikpo = 'Afikpo',
    BeninCity = 'Benin City',
    Auchi = 'Auchi',
    AdoEkiti = 'Ado Ekiti',
    IkereEkiti = 'Ikere Ekiti',
    Enugu = 'Enugu',
    Nsukka = 'Nsukka',
    Gombe = 'Gombe',
    Bajoga = 'Bajoga',
    Owerri = 'Owerri',
    Okigwe = 'Okigwe',
    Dutse = 'Dutse',
    Hadejia = 'Hadejia',
    Kaduna = 'Kaduna',
    Zaria = 'Zaria',
    Kano = 'Kano',
    Rano = 'Rano',
    Katsina = 'Katsina',
    Daura = 'Daura',
    BirninKebbi = 'Birnin Kebbi',
    Yauri = 'Yauri',
    Lokoja = 'Lokoja',
    Okene = 'Okene',
    Ilorin = 'Ilorin',
    Offa = 'Offa',
    Lagos = 'Lagos',
    Ikeja = 'Ikeja',
    Lafia = 'Lafia',
    Karu = 'Karu',
    Minna = 'Minna',
    Suleja = 'Suleja',
    Abeokuta = 'Abeokuta',
    IjebuOde = 'Ijebu Ode',
    Akure = 'Akure',
    OndoCity = 'Ondo City',
    Osogbo = 'Osogbo',
    IleIfe = 'Ile-Ife',
    Ibadan = 'Ibadan',
    Ogbomoso = 'Ogbomoso',
    Jos = 'Jos',
    Bukuru = 'Bukuru',
    PortHarcourt = 'Port Harcourt',
    Okrika = 'Okrika',
    Sokoto = 'Sokoto',
    Wurno = 'Wurno',
    Jalingo = 'Jalingo',
    Wukari = 'Wukari',
    Damaturu = 'Damaturu',
    Potiskum = 'Potiskum',
    Gusau = 'Gusau',
    KauraNamoda = 'Kaura Namoda',
    Abuja = 'Abuja',
    Gwagwalada = 'Gwagwalada'
};

export const CITY_DATA: { cityName: string, stateName: string }[] = [
    { cityName: City.Aba, stateName: State.Abia },
    { cityName: City.Umuahia, stateName: State.Abia },
    { cityName: City.Yola, stateName: State.Adamawa },
    { cityName: City.Jimeta, stateName: State.Adamawa },
    { cityName: City.Uyo, stateName: State.AkwaIbom },
    { cityName: City.Eket, stateName: State.AkwaIbom },
    { cityName: City.Awka, stateName: State.Anambra },
    { cityName: City.Onitsha, stateName: State.Anambra },
    { cityName: City.Bauchi, stateName: State.Bauchi },
    { cityName: City.Azare, stateName: State.Bauchi },
    { cityName: City.Yenagoa, stateName: State.Bayelsa },
    { cityName: City.Brass, stateName: State.Bayelsa },
    { cityName: City.Makurdi, stateName: State.Benue },
    { cityName: City.Gboko, stateName: State.Benue },
    { cityName: City.Maiduguri, stateName: State.Borno },
    { cityName: City.Biu, stateName: State.Borno },
    { cityName: City.Calabar, stateName: State.CrossRiver },
    { cityName: City.Ugep, stateName: State.CrossRiver },
    { cityName: City.Asaba, stateName: State.Delta },
    { cityName: City.Warri, stateName: State.Delta },
    { cityName: City.Abakaliki, stateName: State.Ebonyi },
    { cityName: City.Afikpo, stateName: State.Ebonyi },
    { cityName: City.BeninCity, stateName: State.Edo },
    { cityName: City.Auchi, stateName: State.Edo },
    { cityName: City.AdoEkiti, stateName: State.Ekiti },
    { cityName: City.IkereEkiti, stateName: State.Ekiti },
    { cityName: City.Enugu, stateName: State.Enugu },
    { cityName: City.Nsukka, stateName: State.Enugu },
    { cityName: City.Gombe, stateName: State.Gombe },
    { cityName: City.Bajoga, stateName: State.Gombe },
    { cityName: City.Owerri, stateName: State.Imo },
    { cityName: City.Okigwe, stateName: State.Imo },
    { cityName: City.Dutse, stateName: State.Jigawa },
    { cityName: City.Hadejia, stateName: State.Jigawa },
    { cityName: City.Kaduna, stateName: State.Kaduna },
    { cityName: City.Zaria, stateName: State.Kaduna },
    { cityName: City.Kano, stateName: State.Kano },
    { cityName: City.Rano, stateName: State.Kano },
    { cityName: City.Katsina, stateName: State.Katsina },
    { cityName: City.Daura, stateName: State.Katsina },
    { cityName: City.BirninKebbi, stateName: State.Kebbi },
    { cityName: City.Yauri, stateName: State.Kebbi },
    { cityName: City.Lokoja, stateName: State.Kogi },
    { cityName: City.Okene, stateName: State.Kogi },
    { cityName: City.Ilorin, stateName: State.Kwara },
    { cityName: City.Offa, stateName: State.Kwara },
    { cityName: City.Lagos, stateName: State.Lagos },
    { cityName: City.Ikeja, stateName: State.Lagos },
    { cityName: City.Lafia, stateName: State.Nasarawa },
    { cityName: City.Karu, stateName: State.Nasarawa },
    { cityName: City.Minna, stateName: State.Niger },
    { cityName: City.Suleja, stateName: State.Niger },
    { cityName: City.Abeokuta, stateName: State.Ogun },
    { cityName: City.IjebuOde, stateName: State.Ogun },
    { cityName: City.Akure, stateName: State.Ondo },
    { cityName: City.OndoCity, stateName: State.Ondo },
    { cityName: City.Osogbo, stateName: State.Osun },
    { cityName: City.IleIfe, stateName: State.Osun },
    { cityName: City.Ibadan, stateName: State.Oyo },
    { cityName: City.Ogbomoso, stateName: State.Oyo },
    { cityName: City.Jos, stateName: State.Plateau },
    { cityName: City.Bukuru, stateName: State.Plateau },
    { cityName: City.PortHarcourt, stateName: State.Rivers },
    { cityName: City.Okrika, stateName: State.Rivers },
    { cityName: City.Sokoto, stateName: State.Sokoto },
    { cityName: City.Wurno, stateName: State.Sokoto },
    { cityName: City.Jalingo, stateName: State.Taraba },
    { cityName: City.Wukari, stateName: State.Taraba },
    { cityName: City.Damaturu, stateName: State.Yobe },
    { cityName: City.Potiskum, stateName: State.Yobe },
    { cityName: City.Gusau, stateName: State.Zamfara },
    { cityName: City.KauraNamoda, stateName: State.Zamfara },
    { cityName: City.Abuja, stateName: State.FCT },
    { cityName: City.Gwagwalada, stateName: State.FCT },
];